#!/usr/bin/env python3

import csv, subprocess, argparse
import config

def resetKeychain():
    subprocess.call(['security', 'delete-keychain', config.KEYCHAIN_ICLOUD], stderr=subprocess.DEVNULL)
    subprocess.call(['security', 'create-keychain', config.KEYCHAIN_ICLOUD])

def importPasswords(source):
    resetKeychain()
    with open(source, 'r') as fp:
        reader = csv.reader(fp)
        idx = { f: n for n, f in enumerate(next(reader)) }
        for row in reader:
            params = ['-l', row[idx['Title']], '-a', row[idx['Username']], '-s', row[idx['URL']], '-w', row[idx['Password']]]
            subprocess.call(['security', 'add-internet-password'] + params + [config.KEYCHAIN_ICLOUD])

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('passwords', type=str)
    args = parser.parse_args()
    importPasswords(args.passwords)

